version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps: 
      - checkout
      - run: docker build -f Dockerfile.dev -t kalibdev/docker-react .
      - run: docker run kalibdev/docker-react npm run test --CI=true


    